# Copyright (c) 2018-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# https://docs.ansible.com/ansible/latest/modules/group_module.html
- name:
    "group : ensure airflow group exists"
  group:
    name: "{{ airflow_group }}"
  become:
    true

# https://docs.ansible.com/ansible/latest/modules/user_module.html
- name:
    "user : ensure airflow user exists"
  user:
    name: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    shell: "/bin/bash"
  become:
    true

# https://docs.ansible.com/ansible/latest/modules/user_module.html
- name:
    "file : create airflow user home directory"
  file:
    path: "{{ airflow_home }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
  become:
    true
